"""Audit the IEEE build: log scan plus checks on the rendered PDF.

A compiler log alone cannot tell you whether a page is blank, whether the bibliography
ended up before six pages of floats, or whether a table overflowed its column. This script
reads both the log and the rendered PDF.

Writes paper/ieee_format_audit.md and exits non-zero if a hard gate fails.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
TEX = PAPER / "main_ieee.tex"
LOG = PAPER / "main_ieee.log"
PDF = PAPER / "main_ieee.pdf"
OUT = PAPER / "ieee_format_audit.md"


def main() -> None:
    log = LOG.read_text(encoding="utf-8", errors="ignore")
    tex = TEX.read_text(encoding="utf-8")

    overfull = len(re.findall(r"Overfull \\hbox", log))
    underfull = len(re.findall(r"Underfull \\hbox", log))
    undef_ref = len(re.findall(r"Reference `[^']+' on page \d+ undefined", log))
    undef_cite = len(re.findall(r"Citation `[^']+' on page \d+ undefined", log))
    multi_label = len(re.findall(r"Label `[^']+' multiply defined", log))

    labels = re.findall(r"\\label\{([^}]+)\}", tex)
    dup_labels = sorted({x for x in labels if labels.count(x) > 1})

    docclass = re.search(r"\\documentclass\[([^\]]*)\]\{([^}]+)\}", tex)
    cls = f"{docclass.group(2)} [{docclass.group(1)}]" if docclass else "UNKNOWN"

    import pymupdf
    doc = pymupdf.open(PDF)
    pages = doc.page_count
    blank = [i + 1 for i in range(pages) if len(doc[i].get_text().strip()) < 80]
    bib_page = None
    for i in range(pages):
        if "PortSwigger" in doc[i].get_text():
            bib_page = i + 1
    trailing_floats = 0 if bib_page is None else max(0, pages - bib_page)

    has_index_terms = r"\begin{IEEEkeywords}" in tex
    has_abstract = r"\begin{abstract}" in tex
    abstract = tex[tex.index(r"\begin{abstract}"):tex.index(r"\end{abstract}")]
    abs_words = len(re.sub(r"[\\{}$]", " ", abstract).split())
    sections = re.findall(r"\\section\{([^}]+)\}", tex)
    tables = len(re.findall(r"\\begin\{table\*?\}", tex)) + \
        len(re.findall(r"\\input\{\.\./results/tables/ieee/", tex))
    figures = len(re.findall(r"\\begin\{figure\*?\}", tex))

    gates = [
        ("IEEEtran journal class", "IEEEtran" in cls and "journal" in cls, cls),
        ("Abstract present", has_abstract, str(has_abstract)),
        ("Abstract length 150-300 words", 150 <= abs_words <= 300, f"{abs_words} words"),
        ("Index terms present", has_index_terms, str(has_index_terms)),
        ("Overfull boxes = 0", overfull == 0, str(overfull)),
        ("Undefined references = 0", undef_ref == 0, str(undef_ref)),
        ("Undefined citations = 0", undef_cite == 0, str(undef_cite)),
        ("Duplicate labels = 0", not dup_labels and multi_label == 0,
         str(len(dup_labels) + multi_label)),
        ("No blank pages", not blank, str(blank or "none")),
        ("Bibliography is last", trailing_floats == 0,
         f"{trailing_floats} page(s) after bibliography"),
    ]
    failed = [g for g in gates if not g[1]]

    lines = [
        "# IEEE format audit", "",
        "*Generated by `scripts/audit_ieee_format.py`. The rendered PDF is inspected, not",
        "only the compiler log: a log cannot tell you that a page came out blank or that the",
        "bibliography ended up before six pages of floats.*", "",
        "## Gates", "", "| check | result | status |", "|---|---|---|",
    ]
    for name, ok, val in gates:
        lines.append(f"| {name} | {val} | {'PASS' if ok else 'FAIL'} |")

    lines += [
        "", "## Document shape", "",
        f"- Class: `{cls}`",
        f"- Pages: {pages}",
        f"- Sections: {len(sections)}",
        f"- Tables: {tables}",
        f"- Figures: {figures}",
        f"- Underfull boxes: {underfull} (cosmetic; IEEE two-column text stretches)",
        "", "## Section order", "",
    ]
    lines += [f"{i+1}. {s}" for i, s in enumerate(sections)]
    lines += [
        "", "## Notes", "",
        "- Full-width `table*` floats can only take a page top or a dedicated float page.",
        "  An earlier build queued twelve of them and pushed six pages of tables past the",
        "  bibliography; the set was cut to what the argument needs and most of the",
        "  remainder converted to single-column floats.",
        "- Underfull-hbox warnings come from justified two-column text and are not",
        "  visually harmful; overfull boxes, which are, is the gate we hold at zero.",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for name, ok, val in gates:
        print(f"[{'PASS' if ok else 'FAIL'}] {name}: {val}")
    print(f"\npages={pages} tables={tables} figures={figures} underfull={underfull}")
    print(f"-> {OUT}")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
