"""Derive IEEE two-column-safe table files from the generated ones.

The generated tables target a one-column article layout, where `\\linewidth` is the text
width. Under `IEEEtran` in journal mode the body is two columns, so the same file would be
squeezed into a ~3.5 inch column and become unreadable.

This script rewrites each generated table into a full-width float:

    \\begin{table}   -> \\begin{table*}
    \\linewidth      -> \\textwidth

It reads only from `results/tables/` and writes only to `results/tables/ieee/`, so the
original generators remain the single source of truth and nothing is hand-edited. Rerun it
after any summarizer run.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results" / "tables"
DST = SRC / "ieee"

# Tables narrow enough to sit inside a single column keep `table`; everything else is
# promoted to a full-width `table*`.
# Full-width `table*` floats can only be placed at a page top or on a dedicated float
# page. With a dozen of them they queue up and land after the bibliography, which is why
# most tables here stay single-column: a `table` float can also take a column top, so it
# settles near the text that discusses it. Only tables that are genuinely unreadable at
# column width are promoted.
SINGLE_COLUMN = {
    "table_b0_baseline",
    "table_m1_property_matrix",
    "table_async_b0",
    "table_topology_generality",
    "table_backend_generality",
    "table_cached_split",
    "table_formal_mapping",
    "table_economic_sensitivity",
    "table_real_stack_m1",
    "table_m2_results",
    "table_m1_results",
    "table_m2_concurrency",
    "table_m1_concurrency",
    "table_m1_ablation",
    "table_m2_ablation",
    "table_defense_summary",
    "table_failure_modes",
}

HEADER = ("%% Generated by scripts/make_ieee_tables.py from ../{name}.tex\n"
          "%% Do not edit: regenerate instead.\n")


def convert(path: Path) -> str:
    s = path.read_text(encoding="utf-8")
    wide = path.stem not in SINGLE_COLUMN
    if wide:
        s = s.replace(r"\begin{table}[t]", r"\begin{table*}[t]")
        s = s.replace(r"\end{table}", r"\end{table*}")
        s = s.replace(r"\linewidth", r"\textwidth")
    # IEEE captions read better above the rule and in the class's own size; the generated
    # files already put \caption first, so only the float type needed changing.
    s = re.sub(r"\\resizebox\{\\textwidth\}", r"\\resizebox{\\textwidth}", s)
    return HEADER.format(name=path.stem) + s


def main() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    n = 0
    for p in sorted(SRC.glob("table_*.tex")):
        (DST / p.name).write_text(convert(p), encoding="utf-8")
        n += 1
    print(f"wrote {n} IEEE table variants -> {DST}")
    print(f"single-column kept: {sorted(SINGLE_COLUMN)}")


if __name__ == "__main__":
    main()
